name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Do stuff
      run: node do_stuff.js ${{ steps.extract_branch.outputs.branch }}
    # - name: Update version
    #   run: node update_package.js ${{ steps.extract_branch.outputs.branch }}
    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v1
    #   with:
    #     branch: ${{ steps.extract_branch.outputs.branch }}-more
    #     token: ${{ secrets.GITHUB_TOKEN }}
